//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Colorizer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_PtsPath {
            get {
                return ((string)(this["setting_PtsPath"]));
            }
            set {
                this["setting_PtsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_SbetPath {
            get {
                return ((string)(this["setting_SbetPath"]));
            }
            set {
                this["setting_SbetPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_PicsDir {
            get {
                return ((string)(this["setting_PicsDir"]));
            }
            set {
                this["setting_PicsDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_OutDir {
            get {
                return ((string)(this["setting_OutDir"]));
            }
            set {
                this["setting_OutDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string setting_PointsFormat {
            get {
                return ((string)(this["setting_PointsFormat"]));
            }
            set {
                this["setting_PointsFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setting_SelectPtsFolder {
            get {
                return ((bool)(this["setting_SelectPtsFolder"]));
            }
            set {
                this["setting_SelectPtsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public decimal setting_LeapSecs {
            get {
                return ((decimal)(this["setting_LeapSecs"]));
            }
            set {
                this["setting_LeapSecs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setting_PosFromTime {
            get {
                return ((bool)(this["setting_PosFromTime"]));
            }
            set {
                this["setting_PosFromTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setting_CamEventsPath {
            get {
                return ((string)(this["setting_CamEventsPath"]));
            }
            set {
                this["setting_CamEventsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setting_PitchOffset {
            get {
                return ((decimal)(this["setting_PitchOffset"]));
            }
            set {
                this["setting_PitchOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setting_RollOffset {
            get {
                return ((decimal)(this["setting_RollOffset"]));
            }
            set {
                this["setting_RollOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setting_YawOffset {
            get {
                return ((decimal)(this["setting_YawOffset"]));
            }
            set {
                this["setting_YawOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setting_XOffset {
            get {
                return ((decimal)(this["setting_XOffset"]));
            }
            set {
                this["setting_XOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setting_YOffset {
            get {
                return ((decimal)(this["setting_YOffset"]));
            }
            set {
                this["setting_YOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setting_ZOffset {
            get {
                return ((decimal)(this["setting_ZOffset"]));
            }
            set {
                this["setting_ZOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setting_CamAngle {
            get {
                return ((decimal)(this["setting_CamAngle"]));
            }
            set {
                this["setting_CamAngle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setting_TimeOffset {
            get {
                return ((decimal)(this["setting_TimeOffset"]));
            }
            set {
                this["setting_TimeOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2019-09-26")]
        public global::System.DateTime setting_ScanDate {
            get {
                return ((global::System.DateTime)(this["setting_ScanDate"]));
            }
            set {
                this["setting_ScanDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setting_PerPicOutput {
            get {
                return ((bool)(this["setting_PerPicOutput"]));
            }
            set {
                this["setting_PerPicOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<System.Drawing.PointF> setting_CarShadowPoints {
            get {
                return ((global::System.Collections.Generic.List<System.Drawing.PointF>)(this["setting_CarShadowPoints"]));
            }
            set {
                this["setting_CarShadowPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UTM")]
        public string setting_CoordSys {
            get {
                return ((string)(this["setting_CoordSys"]));
            }
            set {
                this["setting_CoordSys"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal setting_TimeScaleFact {
            get {
                return ((decimal)(this["setting_TimeScaleFact"]));
            }
            set {
                this["setting_TimeScaleFact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setting_XYZRGBI {
            get {
                return ((bool)(this["setting_XYZRGBI"]));
            }
            set {
                this["setting_XYZRGBI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setting_CheckScanDate {
            get {
                return ((bool)(this["setting_CheckScanDate"]));
            }
            set {
                this["setting_CheckScanDate"] = value;
            }
        }
    }
}
